apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
      nodePort: 30004
  selector:
    service: udaconnect-location-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-location-consumer
  name: udaconnect-location-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-location-consumer
  template:
    metadata:
      labels:
        service: udaconnect-location-consumer
    spec:
      containers:
        - image: ualali/udaconnect-location-consumer:latest
          name: udaconnect-location-consumer
          imagePullPolicy: Always
          env:
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_NAME
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: db-env
                  key: DB_PORT
      restartPolicy: Always
